config/routes.rb
FreeRanger::Application.routes.draw do
  resources :rangers

end

app/models/ranger.rb
class Ranger < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rangers_controller.rb
class RangersController < ApplicationController
  before_action :set_ranger, only: [:show, :edit, :update, :destroy]

  # GET /rangers
  # GET /rangers.json
  def index
    @rangers = Ranger.all
  end

  # GET /rangers/1
  # GET /rangers/1.json
  def show
  end

  # GET /rangers/new
  def new
    @ranger = Ranger.new
  end

  # GET /rangers/1/edit
  def edit
  end

  # POST /rangers
  # POST /rangers.json
  def create
    @ranger = Ranger.new(ranger_params)

    respond_to do |format|
      if @ranger.save
        format.html { redirect_to @ranger, notice: 'Ranger was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ranger }
      else
        format.html { render action: 'new' }
        format.json { render json: @ranger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rangers/1
  # PATCH/PUT /rangers/1.json
  def update
    respond_to do |format|
      if @ranger.update(ranger_params)
        format.html { redirect_to @ranger, notice: 'Ranger was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ranger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rangers/1
  # DELETE /rangers/1.json
  def destroy
    @ranger.destroy
    respond_to do |format|
      format.html { redirect_to rangers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranger
      @ranger = Ranger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ranger_params
      params.require(:ranger).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rangers_helper.rb
module RangersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreeRanger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rangers/_form.html.erb
<%= form_for(@ranger) do |f| %>
  <% if @ranger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranger.errors.count, "error") %> prohibited this ranger from being saved:</h2>

      <ul>
      <% @ranger.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rangers/edit.html.erb
<h1>Editing ranger</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranger %> |
<%= link_to 'Back', rangers_path %>

app/views/rangers/index.html.erb
<h1>Listing rangers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rangers.each do |ranger| %>
      <tr>
        <td><%= ranger.name %></td>
        <td><%= ranger.color %></td>
        <td><%= link_to 'Show', ranger %></td>
        <td><%= link_to 'Edit', edit_ranger_path(ranger) %></td>
        <td><%= link_to 'Destroy', ranger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ranger', new_ranger_path %>

app/views/rangers/new.html.erb
<h1>New ranger</h1>

<%= render 'form' %>

<%= link_to 'Back', rangers_path %>

app/views/rangers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ranger.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @ranger.color %>
</p>

<%= link_to 'Edit', edit_ranger_path(@ranger) %> |
<%= link_to 'Back', rangers_path %>